/** Villes SENGA — aligné DRC_SERVICE_AREAS / admin MOVA_CITIES. */
export const MOVA_CITIES = [
  "Kinshasa",
  "Lubumbashi",
  "Goma",
  "Bukavu",
  "Kisangani",
  "Mbuji-Mayi",
  "Kananga",
  "Matadi",
  "Boma",
  "Kolwezi",
  "Likasi",
  "Tshikapa",
  "Mbandaka",
  "Kindu",
  "Bunia",
  "Butembo",
  "Beni",
  "Uvira",
  "Kalemie",
  "Kamina",
  "Gbadolite",
  "Gemena",
  "Boende",
  "Lisala",
  "Isiro",
  "Buta",
  "Inongo",
  "Bandundu",
  "Kikwit",
  "Kenge",
  "Kabinda",
  "Lusambo",
] as const;
