ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'RESTAURANT_CONFIRMED';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_PICKUP';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS "isAcceptingOrders" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS "prepTimeMin" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS "ownerUserId" TEXT;
CREATE INDEX IF NOT EXISTS "restaurants_ownerUserId_idx" ON restaurants("ownerUserId");
