-- AlterEnum
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'SOS';

-- AlterTable
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "lat" DOUBLE PRECISION;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "lng" DOUBLE PRECISION;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "referenceType" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "referenceId" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "isEmergency" BOOLEAN NOT NULL DEFAULT false;
